version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "my-serverless-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-t8cggz6hc2jn"
s3_prefix = "my-serverless-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
